import { useState } from 'react';
import { Icon } from './Icon.jsx';
import { integrations } from '../data/platformData.js';

const automation = [
  { trigger: 'Interview completed', action: 'Create structured feedback request', channel: 'Greenhouse' },
  { trigger: 'High-priority integrity alert', action: 'Notify Trust reviewer', channel: 'Slack' },
  { trigger: 'Consent withdrawn', action: 'Start downstream deletion workflow', channel: 'Event fabric' },
];

export function Integrations({ onToast }) {
  const [showConnected, setShowConnected] = useState(true);
  const visible = showConnected ? integrations : integrations.filter((item) => item.status !== 'Connected');
  return (
    <main className="page integrations-page">
      <section className="integration-hero surface-card"><div><span className="pill pill-violet"><Icon name="plug" size={14} /> OPEN, CONTROLLED ECOSYSTEM</span><h2>Your hiring stack, <em>connected with intent.</em></h2><p>Bring scheduling, ATS, HRIS, identity, communications, and data workflows together through governed, observable connections.</p><div className="integration-hero-actions"><button className="button button-primary" onClick={() => onToast('Connector marketplace opened. Choose a provider to begin its OAuth or admin-approved setup.')}><Icon name="plus" size={17} /> Add integration</button><button className="button button-secondary" onClick={() => onToast('Webhook developer console opened with a tenant-scoped test endpoint.')}><Icon name="terminal" size={17} /> Developer console</button></div></div><div className="integration-art"><span className="hub-icon"><Icon name="plug" size={30} /></span><i className="hub-line h1"/><i className="hub-line h2"/><i className="hub-line h3"/><span className="orbit-app app-one">GH</span><span className="orbit-app app-two">SL</span><span className="orbit-app app-three">GW</span></div></section>
      <section className="integration-toolbar"><div><span className="section-kicker">TENANT CONNECTIONS</span><h2>Managed integrations</h2></div><div className="filter-chips"><button className={`filter-chip ${showConnected ? 'is-active' : ''}`} onClick={() => setShowConnected(true)}>All ({integrations.length})</button><button className={`filter-chip ${!showConnected ? 'is-active' : ''}`} onClick={() => setShowConnected(false)}>Needs attention</button></div></section>
      <section className="integration-card-grid">{visible.map((integration) => <article className="surface-card integration-card" key={integration.name}><div className="integration-card-head"><span className={`integration-logo logo-${integration.accent}`}>{integration.initials}</span><button className="icon-button tiny" aria-label={`Configure ${integration.name}`} onClick={() => onToast(`${integration.name} configuration opens with credentials masked and access audited.`)}><Icon name="more" size={18} /></button></div><h3>{integration.name}</h3><p>{integration.type}</p><div className="integration-card-foot"><span className={integration.status === 'Connected' ? 'status-chip status-mint' : 'status-chip status-amber'}>{integration.status === 'Connected' && <i className="tiny-live-dot" />}{integration.status}</span><small>{integration.status === 'Connected' ? `Synced ${integration.sync}` : 'Action required'}</small></div></article>)}</section>
      <section className="automation-layout"><article className="surface-card automation-card"><div className="surface-header"><div><span className="section-kicker">NO-CODE AUTOMATION</span><h2>Trusted workflow recipes</h2></div><button className="text-button" onClick={() => onToast('The visual workflow builder is available for permitted administrators.')}>Create recipe <Icon name="arrowUpRight" size={14} /></button></div><div className="automation-list">{automation.map((item) => <article key={item.trigger}><span className="automation-trigger"><Icon name="activity" size={16} /></span><div><small>WHEN</small><b>{item.trigger}</b></div><Icon name="chevronRight" size={17} /><div><small>THEN</small><b>{item.action}</b></div><span className="automation-channel">{item.channel}</span><button className="icon-button tiny" aria-label={`Edit ${item.trigger}`}><Icon name="chevronRight" size={16} /></button></article>)}</div></article><aside className="surface-card webhook-card"><span className="section-kicker">WEBHOOK DELIVERY</span><h2>Last 24 hours</h2><strong className="webhook-number">24,882</strong><p>signed deliveries across 8 subscriptions</p><div className="webhook-bars"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><button className="button button-secondary full" onClick={() => onToast('Delivery logs are filtered by tenant and redact sensitive payload fields.')}>Inspect delivery logs</button></aside></section>
    </main>
  );
}
