apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: tempo
        queries:
          - name: "Request rate"
            query: "sum(rate(http_server_request_duration_seconds_count[$__rate_interval])) by (http_route)"
          - name: "Error rate"
            query: "sum(rate(http_server_request_duration_seconds_count{http_status_code=~\"5..\"}[$__rate_interval])) by (http_route)"
          - name: "Duration P99"
            query: "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, http_route))"
      tracesToLogs:
        datasourceUid: tempo
      nodeGraph:
        enabled: true
    uid: tempo
